#!/bin/bash
MSCOCO_DIR="/home/superNLP/usb_hdd/cocodata"
INCEPTION_CHECKPOINT="/home/superNLP/im2txt/data/inception_v3.ckpt"
MODEL_DIR="/home/superNLP/usb_hdd/model"
NLTK_DATA="/home/superNLP/usb_hdd/nltk_data"
VOCAB_FILE="/home/superNLP/usb_hdd/cocodata/word_counts.txt"
CHECKPOINT_DIR="/home/superNLP/udb_hdd/model/train"
CHECKPOINT_PATH="/home/superNLP/usb_hdd/model/train"
VALIDATEGLOBAL=true
IMAGE_DIR="/home/superNLP/usb_hdd/cocodata/raw-data/val2014"
